### ISSUE TITLE
CHARTE Re travailler la mise à disposition des espaces perso

### ISSUE THREAD

**Issue by CortneyKnorr** [Association-Mallouestan/docs.mallouestan.github.io#58]
- Mise à disposition des espaces pour les groupes 
- Etat de l'espace perso lors de la restitution de cet espace 
- Cadre de la responsabilité indiv/collective à l'égard des travaux sur un espace perso

**Comment by Tobiot** [comment]
- Gestion / modification des extérieurs des espaces perso
